#!/usr/bin/env bash
# Fails if container logs contain credentials, tokens or other secrets (milestone M2.5, threat model I-03).
#
# Run after the integration test suite, which generates realistic traffic: sign-ins, registrations,
# password resets, token refreshes and admin operations.
#
# Usage: scripts/ci/scan-logs-for-secrets.sh [path-to-env-file]
set -euo pipefail

env_file="${1:-.env}"
log_file="$(mktemp)"
trap 'rm -f "$log_file"' EXIT

docker compose logs --no-color > "$log_file" 2>&1
echo "Scanning $(wc -l < "$log_file") log lines..."

failures=0
check() {
  local description="$1" pattern="$2"
  local count
  count=$(grep -cE -- "$pattern" "$log_file" || true)
  if [ "$count" -gt 0 ]; then
    echo "FAIL: $description ($count occurrences)"
    grep -oE -- "$pattern" "$log_file" | head -3 | cut -c1-60 | sed 's/^/      /'
    failures=$((failures + 1))
  else
    echo "ok:   $description"
  fi
}

# Tokens: JWTs (access, refresh, ID and action tokens) always start with a base64url-encoded JSON header.
check "JSON Web Tokens"                    'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}'
check "authorization codes in URLs"        '[?&]code=[0-9a-f]{8}-[0-9a-f-]{27,}'
check "action token links"                 'action-token\?key='
check "client secrets in parameters"       'client_secret=[^&[:space:]"]{8,}'
check "refresh tokens in parameters"       'refresh_token=[^&[:space:]"]{8,}'

# Passwords generated by the integration and end-to-end tests.
check "test user passwords"                '(Pw|Reset)-[0-9a-f]{32}'
check "e2e user passwords"                 'Bff-[0-9a-f]{8}-[0-9a-f]{4}-'

# Every secret configured for the local stack.
if [ -f "$env_file" ]; then
  while IFS='=' read -r name value; do
    case "$name" in
      *PASSWORD*|*SECRET*)
        if [ -n "$value" ] && grep -qF -- "$value" "$log_file"; then
          echo "FAIL: value of $name appears in logs"
          failures=$((failures + 1))
        fi
        ;;
    esac
  done < <(grep -E '^[A-Z_]+=' "$env_file")
  echo "ok:   configured secrets checked"
fi

if [ "$failures" -gt 0 ]; then
  echo "$failures secret-leak check(s) failed."
  exit 1
fi
echo "No secrets found in logs."
