using System.Security.Cryptography;
using Dovepeak.Identity.Keycloak;
using Microsoft.Extensions.DependencyInjection;

namespace Dovepeak.Identity.DevTool;

/// <summary>
/// Provisions everything the Next.js BFF example and the protected API example need (milestone M1.2).
/// Idempotent: re-running reuses the realm and rotates the BFF secret so the written .env.local is always valid.
/// </summary>
internal static class DemoSetup
{
    public const string ApiAudience = "dovepeak-demo-api";
    private const string ClientId = "demo-bff";
    private const string DemoEmail = "demo@example.test";

    public static async Task<int> RunAsync(IServiceProvider services, Uri publicUrl, CommandArgs args)
    {
        var admin = services.GetRequiredService<KeycloakAdminClient>();
        var appUrl = new Uri(args.Get("app-url") ?? "http://localhost:3000");
        var realm = RealmName.Parse("dp-demo");
        var ct = CancellationToken.None;

        var realmOutcome = await admin.CreateRealmAsync(realm, "Dovepeak Demo", ct);
        Console.WriteLine($"Realm {realm}: {realmOutcome}");

        var client = await admin.CreateClientAsync(realm, new ClientRegistration(ClientId, ClientKind.Confidential)
        {
            Name = "Demo BFF (Next.js)",
            RedirectUris = [new Uri(appUrl, "/api/auth/callback")],
            PostLogoutRedirectUris = [new Uri(appUrl, "/")],
            WebOrigins = [appUrl],
            Audiences = [ApiAudience],
        }, ct);
        var secret = client.Secret ?? await admin.RegenerateClientSecretAsync(realm, client.Id, ct);
        Console.WriteLine($"Client {ClientId}: {client.Outcome}");

        string? password = null;
        if (realmOutcome == ProvisioningOutcome.Created)
        {
            password = $"Demo-{Convert.ToHexString(RandomNumberGenerator.GetBytes(6))}";
            await admin.CreateUserAsync(realm, DemoEmail, password, emailVerified: true, ct);
        }

        var issuer = new Uri(publicUrl, $"realms/{realm}");
        var envPath = Path.Combine(FindRepositoryRoot(), "examples", "nextjs-bff", ".env.local");
        await File.WriteAllTextAsync(envPath, $"""
            # Generated by: dotnet run --project tools/Dovepeak.Identity.DevTool -- demo-setup
            # Local development only. Never commit this file.
            DOVEPEAK_ISSUER={issuer}
            DOVEPEAK_CLIENT_ID={ClientId}
            DOVEPEAK_CLIENT_SECRET={secret}
            APP_URL={appUrl.GetLeftPart(UriPartial.Authority)}
            SESSION_REDIS_URL=redis://:valkey_local_only@localhost:6379/1
            PROTECTED_API_URL=http://localhost:5301

            """, ct);

        Console.WriteLine($"""

            Wrote {envPath}

            Next steps:
              1. Start the protected API:
                 dotnet run --project examples/dotnet-protected-api/Dovepeak.Examples.ProtectedApi -- \
                   --Auth:Issuer={issuer} --Auth:Audience={ApiAudience} --Auth:RequireHttpsMetadata=false
              2. Start the app:
                 cd examples/nextjs-bff && npm install && npm run dev
              3. Open {appUrl}
            """);

        Console.WriteLine(password is null
            ? $"\nDemo user {DemoEmail} already exists (password was shown when it was created). You can also register a new account."
            : $"\nDemo user: {DemoEmail} / {password}   (shown once)");

        return 0;
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(Environment.CurrentDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Dovepeak.Identity.slnx")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new ArgumentException("Run this command from inside the repository.");
    }
}
