// <auto-generated />
using System;
using Dovepeak.Identity.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dovepeak.Identity.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261009143958_InitialAuditStore")]
    partial class InitialAuditStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dovepeak.Identity.Persistence.Audit.AuditCheckpoint", b =>
                {
                    b.Property<string>("Realm")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("realm");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("LastEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Realm", "Source")
                        .HasName("pk_audit_checkpoints");

                    b.ToTable("audit_checkpoints", (string)null);
                });

            modelBuilder.Entity("Dovepeak.Identity.Persistence.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("Error")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Realm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("realm");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_event_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("Realm", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_realm_occurred_at");

                    b.HasIndex("Realm", "Source", "SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_events_realm_source_source_event_id");

                    b.HasIndex("Realm", "UserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_realm_user_id_occurred_at");

                    b.ToTable("audit_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
